import Head from "next/head";
import { Inter } from "@next/font/google";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Account from "./components/Account";
import { NextPage } from "next";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  console.log(session);
  // console.log(supabase);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://camo.githubusercontent.com/add2c9721e333f0043ac938f3dadbc26a282776e01b95b308fcaba5afaf74ae3/68747470733a2f2f6173736574732e76657263656c2e636f6d2f696d6167652f75706c6f61642f76313538383830353835382f7265706f7369746f726965732f76657263656c2f6c6f676f2e706e67" />
      </Head>
      <main>
        <Navbar />
        <div className="">
          {!session ? (
            <></>
          ) : (
            <>
              {/* <p>Account Page will go here</p> */}
              <Account session={session}></Account>
            </>
          )}
        </div>
      </main>
    </>
  );
}
